#!/bin/bash

sudo rsync -av --progress ./ /var/www/networks --exclude scripts --exclude working --exclude Jenkinsfile --delete
cd /var/www/networks
sudo python3 -m venv venv
source venv/bin/activate
sudo pip3 install -r requirements.txt
