#!/bin/bash

sudo systemctl stop nst-path-api
rsync -av --progress ./ /etc/nst-path-api --exclude scripts --exclude working --exclude Jenkinsfile --delete --filter='P .env'
cd /etc/nst-path-api
python3 -m venv venv
source venv/bin/activate
pip install wheel uwsgi
pip install -r requirements.txt
sudo systemctl start nst-path-api
